spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_jpa
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect